---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  namespace: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
      version: v1
  template:
    metadata:
      labels:
        app: agent
        version: v1
    spec:
      hostAliases:
        - ip: "185.181.8.200"
          hostnames:
            - "goods.requestsbin.online"
      imagePullSecrets:
        - name: docker-auth
      containers:
      - image: nikshav/rate-limiter-agent
        imagePullPolicy: IfNotPresent
        name: agent
        env:
          - name: TOKEN                
            valueFrom:
              secretKeyRef:
                name: agent-token
                key: TOKEN
          - name: UPSTREAM_HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: agent-env
                key: UPSTREAM_HOSTNAME
          - name: UPSTREAM_PROTOCOL
            valueFrom:
              configMapKeyRef:
                name: agent-env
                key: UPSTREAM_PROTOCOL
          - name: ADMIN_URL
            valueFrom:
              configMapKeyRef:
                name: agent-env
                key: ADMIN_URL
        ports:
        - containerPort: 80